### ISSUE TITLE
pinpong loop bug in Ubuntu

### ISSUE THREAD

**Issue by MoorPoor** [brunoherbelin/vimix#117]
Pingpong loop is not working anymore for me at ubuntu 23.10 with nvidia card and flatpak beta (same in stable)
it sticks to the end and is not playing backwards.
![grafik](https://github.com/brunoherbelin/vimix/assets/60827766/206cc2ee-c4b8-4c41-99bb-a90ace2d3d73)

While I'm at it, would it be possible to add another curve (just another colour?) for the playback speed so that it could be changed as the opacity? the playhead would then slow down or speed up. I can imagine that's a problem, but it would be fantastic!

**Comment by MoorPoor** [comment]
That doesn't belong here, but since it just occurred to me, alpha key has a problem with the opacity fading in and out
![Peek 2023-12-19 14-01](https://github.com/brunoherbelin/vimix/assets/60827766/34bb0e20-2ea0-49fa-8aa5-f6ab6c5391d4)

**Comment by brunoherbelin** [comment]
> That doesn't belong here, but since it just occurred to me, alpha lumakey has a problem with the opacity fading in and out

Indeed, that was the expected behavior considering the fading operates a fade to black, and the lumakey is making the transparency by color... 

So, and because this was under the hood but never requested, I added a mode for fading the alpha instead of the color in the media player : 

![image](https://github.com/brunoherbelin/vimix/assets/60393189/d4b7d988-c973-4c1c-99c9-9b54cea1b587)

Then, the lumakey code was fixed to take this change into account and you should now have the effect you expected.
You can check it in Beta e8daeb5f30fa949871f85ce63ace149649e973fc

**Comment by brunoherbelin** [comment]
> Pingpong loop is not working anymore 

yes indeed, same here... probably something changed in gstreamer :disappointed: 

But should be fixed now ! You can check if it works in Beta a529b34f99ba1174620aab77bd51425022abdd48

**Comment by MoorPoor** [comment]
Hei!
 in the latest install in 0.8.2b-3 the pingpong bug is still there, just changed a bit.
 sorry for asking: the snap edge version is the beta version? or I need to compile if you ask for beta testing?
 Thanks!

**Comment by brunoherbelin** [comment]
Arg :disappointed:  ... 

I tested with snap and with flatpak releases (0.8.2b) and the bouncing works fine here on Ubuntu 23.10.

One thing which might prevent gstreamer from playing a video backward is the hardware decoder on your machine: did you try forcing software decoder for that video?

![image](https://github.com/brunoherbelin/vimix/assets/60393189/b121068f-8403-4ba1-b32a-2681811db75a)

**Comment by MoorPoor** [comment]
I just noticed that apple pro-res is pingponging well. it is anyway in software rendering.
mp4 files still not play backwards even in software rendering - at my machine ubuntu 23.10 snap version

**Comment by brunoherbelin** [comment]
Thanks for your tenacity on this ! I could replicate the problem with some specific videos: I think (almost sure) that the problem is caused by the absence of a keyframe next to the end of the video where it shall bounce: it jumps back and forth between keyframes at timestamps that are invalid.

First, two potential solutions for you;

A. Reencode your video:

    ffmpeg -i input.mp4  -g 1 output.mp4

Running this on your input video will re-encode the video with every frame as a key frame, and this should make the backward playing and bouncing work without problem. 
NB: this would be adapted to short duration videos, which I suspect is what you have.

B. Cut the video segment before the end;

![image](https://github.com/brunoherbelin/vimix/assets/60393189/54f1cdc0-aeca-490f-89ae-31a7b22fb917)

Using the timeline cissors, remove the end few frames (right dark area in timeline above)



Second, now that I have a lead to the understanding of the problem, I might find a workaround and will let you know !

**Comment by brunoherbelin** [comment]
quick follow-up : bug should be fixed in Beta f8b5b1db9c782837d22386446488d133696e468a

If you can try the [Beta version](https://github.com/brunoherbelin/vimix/blob/master/flatpak/README.md#build-local-beta-flatpack-package-of-vimix), thanks for indicating if this solves your problem.

**Comment by lupin3rd** [comment]
Hi Bruno and MoorPoor, i notice the same problem with bounce.
I confirm that with reencoded video (keyframe in every frame) all works fine also with nvidia and hardware decode.
Then solution is only to reencode videos? or Vimix can do somethink when load videos?

**Comment by brunoherbelin** [comment]
Well, the problem should be fixed, and bouncing should work on any videos (at least on videos I tested using latest with Beta). But indeed, no video decoder can do miracles, so a good video file with lots of key-frames is best for smooth playback!

I checked with gstreamer (instead of ffmpeg) to do a re-encoding and to add a 're-encode video' option in vimix. Should be doable: would that be useful?

**Comment by lupin3rd** [comment]
I tested last beta, my H264 videos have a lot of problem with bounce :-(
The only solution is to re-encode.
The option to add a re-encoded video is useful because people don't read issue's discussions or documentation :-) Not for us.
